source 'https://rubygems.org'
ruby '2.6.3'

gem 'sinatra'
gem 'mysql2'
gem 'rake'
gem 'irb'
gem 'activerecord'
gem 'sinatra-activerecord'
gem "puma", ">= 4.3.8"
gem 'sinatra'
gem 'sinatra-cross_origin'

group :development do
    gem 'byebug'
end

group :test do
  gem 'byebug'
  gem 'database_cleaner'
  gem 'factory_bot'
  gem 'minitest'
  gem 'pry'
  gem 'rack-test'
end